travis:
  secure:
    BINSTAR_TOKEN: Ex/KDhsyfrWrlumrHDAIZ6sYV+MfvnKFrHHoeWq5x8/gVS8vef3OmG71mclju1NiyurQG5vEraO5vo76T8SVwj6e2s2DYOkllqSwTxUVlshPl4Or8tbA6HnsUvGAHY/o4EOgbJ0b4th8557O0QE6EqPyqxinBAQPMflUFqtMd9B+hLWtWHJ8Cp7nQdufwSjSb/lkioDCyiJcpDRG/Ysjm8dUiWOpQ4VhSA8OXmfF/2S9g+ysSpG9aL902s3gFna2hDuhAtf/c5VJH5BdOfXM4Xcp5j+1qDwXZ+XiB5HkJog2pKrJBFxuaRvpUDrdn13m5s0E6H+tzy2UYNXD1OHXcwIaghVpOPF4HZWzs6orUjNuMo63232t2W3D+iqIEKYcaACU8nYjGsh+iYDPL1KDF0zaTBVFDEgNWjLNrzDoRPKY0n87htfwWG2TIqV/Jn0hSThl+LXhzii2PMgP4r7oYK5CWEaRt55QIriDPHEXLhisA+Q6n1IGprT8HauXb9W+Zj4DkUizUnjGPM7+hUGaGW+kpmg0gByqkZmrIv9KxEK/Qu3ekedEjJig+2ypuuKRKAbAtXIv61EzNGXP+ekCgf8Oggn0PViS4zwW4/OQrT+HHBuJcBq26v9tOFtEIvTIbcniEUcMjPK2hqTlv0Er2tS/XpxSA0Q39lLYloYaN1o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
